apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-reader
  labels:
    {{- include "verticle-gateway-operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "deployments", "services", "serviceaccounts", "secrets"]
  verbs: ["get", "watch", "list", "update", "delete", "create"]

- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "watch", "list"]

- apiGroups: [ "networking.x-k8s.io" ]
  resources: [ "gateways", "gatewayclasses" ,"httproutes" ]
  verbs: [ "get", "watch", "list", "update" ]