server:
  port: 9001

javaoperatorsdk:
  controllers:
    customservicecontroller:
      retry:
        maxAttempts: 3

gateway.image.pullPolicy: Always
#IfNotPresent

gateways:
  apikey:
    containerImage: verticleio/spring-cloud-gateway:0.0.1-SNAPSHOT
    controllerName: io.verticle.operator/gateway-apikey


management:
  info:
    git:
      mode: "full"
  endpoint:
    health:
      probes:
        enabled: true